<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Author List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="/style/authorsList.css">
</head>

<body>

<div class = "table-wrapper">
    <table>
        <tr>
            <th>Author</th>
            <th>Books</th>
            <th>Actions</th>
        </tr>

        <?php foreach ($authors as $author): ?>
            <tr>

                <td>
                    <i class="fa-solid fa-user author-icon"></i>
                    <a href="../index.php?page=authorBooks&author_id=<?= $author['id'] ?>">
                            <?= htmlspecialchars($author['first_name']) ?>
                            <?= htmlspecialchars($author['last_name']) ?></a>
                </td>

                <td> <span class="book-count">0</span> </td>

                <td class="actions">
                    <a class="button edit" href="../index.php?page=editAuthor&id=<?= $author['id'] ?>">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <a class="button delete" href="../index.php?page=deleteAuthor&id=<?= $author['id'] ?>">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </td>

            </tr>
        <?php endforeach; ?>

    </table>
</div>

<a class="add" href="../index.php?page=createAuthor">
    <i class="fa-solid fa-plus"></i>
</a>

</body>
</html>

