<!DOCTYPE html>
<html lang="en">
<head>
    <title>Author Create</title>
    <link rel="stylesheet" href="../style/createEditAuthor.css">
</head>
<body>

<div class="form-container">
    <h2>Author Create</h2>
    <hr style="border: 1px solid #BEDCFE;">

    <form method="post" action="">
        <label for="first_name">First name</label>
        <input type="text" name="first_name" id="first_name"  value="<?= htmlspecialchars($_POST['first_name'] ?? '') ?>">

        <?php if (!empty($errors['first_name'])): ?>
            <div class="error-msg" style="color: red;"><?= htmlspecialchars($errors['first_name']) ?></div>
        <?php endif; ?>

        <label for="last_name">Last name</label>
        <input type="text" name="last_name" id="last_name"  value="<?= htmlspecialchars($_POST['last_name'] ?? '') ?>">

        <?php if (!empty($errors['last_name'])): ?>
            <div class="error-msg" style="color: red;"><?= htmlspecialchars($errors['last_name']) ?></div>
        <?php endif; ?>

        <div class="btn-wrapper">
            <button type="submit">Save</button>
        </div>

        <?php if (!empty($errors['general'])): ?>
            <div class="error-msg" style="color: red; margin-top: 10px;"><?= htmlspecialchars($errors['general']) ?></div>
        <?php endif; ?>
    </form>

</div>

</body>
</html>
