<!DOCTYPE html>
<html lang="en">
<head>
    <title>Edit Author</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="/style/createEditAuthor.css">
</head>
<body>

<div class="form-container">
    <h2>Edit Author (ID: <?= htmlspecialchars($author->getId())?>)</h2>
    <hr style="border: 1px solid #BEDCFE;">
    <form method="post" action="">

        <label for="first_name">First Name</label>
        <input type="text" id="first_name" name="first_name" value="<?= htmlspecialchars($author->getFirst()) ?>">

        <?php if (!empty($errors['first_name'])): ?>
            <div class="error-msg" style="color: red;"><?= htmlspecialchars($errors['first_name']) ?></div>
        <?php endif; ?>

        <label for="last_name">Last Name:</label>
        <input type="text" id="last_name" name="last_name" value="<?= htmlspecialchars($author->getLastName()) ?>">

        <?php if (!empty($errors['last_name'])): ?>
            <div class="error-msg" style="color: red;"><?= htmlspecialchars($errors['last_name']) ?></div>
        <?php endif; ?>

        <div class="btn-wrapper">
            <button type="submit">Save</button>
        </div>

        <?php if (!empty($errors['general'])): ?>
            <div class="error-msg" style="color: red; margin-top: 10px;"><?= htmlspecialchars($errors['general']) ?></div>
        <?php endif; ?>

    </form>
</div>

</body>
</html>